import { Business, Booking, Order } from "./types";

export const CATEGORIES = [
  { id: "restaurant", label: "Restaurants", icon: "coffee" },
  { id: "artisan", label: "Artisans", icon: "tool" },
  { id: "beauty", label: "Beauté", icon: "scissors" },
  { id: "health", label: "Santé", icon: "heart" },
  { id: "education", label: "Formation", icon: "book" },
  { id: "auto", label: "Auto", icon: "truck" },
  { id: "tech", label: "Tech & IT", icon: "monitor" },
  { id: "cleaning", label: "Nettoyage", icon: "home" },
];

export const MOCK_BUSINESSES: Business[] = [
  {
    id: "b1",
    name: "Restaurant Chez Mamie",
    category: "restaurant",
    categoryIcon: "coffee",
    description: "Cuisine traditionnelle africaine dans un cadre chaleureux. Nos plats mijotés au feu de bois vous feront voyager.",
    phone: "+228 90 12 34 56",
    email: "chezmamie@gmail.com",
    address: "Rue des Artisans, Quartier Bè",
    city: "Lomé",
    rating: 4.7,
    reviewCount: 128,
    isOpen: true,
    openHour: "08:00",
    closeHour: "22:00",
    hasDelivery: true,
    distance: "1.2 km",
    isVerified: true,
    services: [
      { id: "s1", title: "Fufu & Soupe Graine", description: "Fufu de manioc avec soupe de graine de palme et poisson fumé", price: 2500, currency: "FCFA" },
      { id: "s2", title: "Riz Sauté Spécial", description: "Riz sauté aux légumes, poulet grillé et sauce piquante maison", price: 3500, currency: "FCFA" },
      { id: "s3", title: "Brochettes de Boeuf", description: "Brochettes marinées au gingembre et ail, sauce arachide", price: 2000, currency: "FCFA" },
      { id: "s4", title: "Boisson Locale", description: "Jus de bissap, gingembre ou tamarind fait maison", price: 500, currency: "FCFA" },
    ],
    openingHours: {
      Lun: { open: "08:00", close: "22:00", closed: false },
      Mar: { open: "08:00", close: "22:00", closed: false },
      Mer: { open: "08:00", close: "22:00", closed: false },
      Jeu: { open: "08:00", close: "22:00", closed: false },
      Ven: { open: "08:00", close: "23:00", closed: false },
      Sam: { open: "09:00", close: "23:00", closed: false },
      Dim: { open: "10:00", close: "20:00", closed: false },
    },
  },
  {
    id: "b2",
    name: "Salon Élégance & Style",
    category: "beauty",
    categoryIcon: "scissors",
    description: "Coiffure, manucure et soins du visage. Nos coiffeurs experts vous offrent un relooking complet.",
    phone: "+228 91 23 45 67",
    address: "Avenue de la Victoire, Centre-ville",
    city: "Lomé",
    rating: 4.5,
    reviewCount: 89,
    isOpen: true,
    openHour: "09:00",
    closeHour: "19:00",
    hasDelivery: false,
    distance: "0.8 km",
    isVerified: true,
    services: [
      { id: "s5", title: "Coiffure Femme", description: "Tressage, défrisage, perruque ou coiffure naturelle", price: 5000, currency: "FCFA" },
      { id: "s6", title: "Coupe Homme", description: "Coupe + dégradé + barbe", price: 2000, currency: "FCFA" },
      { id: "s7", title: "Manucure Complète", description: "Soin des mains, ongles posés, vernis gel", price: 3500, currency: "FCFA" },
      { id: "s8", title: "Soin du Visage", description: "Nettoyage en profondeur + masque hydratant", price: 4000, currency: "FCFA" },
    ],
    openingHours: {
      Lun: { open: "09:00", close: "19:00", closed: false },
      Mar: { open: "09:00", close: "19:00", closed: false },
      Mer: { open: "09:00", close: "19:00", closed: false },
      Jeu: { open: "09:00", close: "19:00", closed: false },
      Ven: { open: "09:00", close: "20:00", closed: false },
      Sam: { open: "08:00", close: "20:00", closed: false },
      Dim: { open: "10:00", close: "15:00", closed: false },
    },
  },
  {
    id: "b3",
    name: "Atelier Menuiserie Kokou",
    category: "artisan",
    categoryIcon: "tool",
    description: "Fabrication sur mesure de meubles et boiseries. Qualité artisanale, livraison à domicile.",
    phone: "+228 97 34 56 78",
    address: "Zone Industrielle de Kégué",
    city: "Lomé",
    rating: 4.8,
    reviewCount: 52,
    isOpen: true,
    openHour: "07:30",
    closeHour: "18:00",
    hasDelivery: true,
    distance: "3.5 km",
    isVerified: true,
    services: [
      { id: "s9", title: "Porte en Bois Sur Mesure", description: "Fabrication et pose de porte en bois massif", price: 85000, currency: "FCFA" },
      { id: "s10", title: "Armoire 2 Portes", description: "Armoire coulissante avec miroir, finition au choix", price: 120000, currency: "FCFA" },
      { id: "s11", title: "Table à Manger", description: "Table 6 personnes en bois teck ou acacia", price: 95000, currency: "FCFA" },
      { id: "s12", title: "Réparation Meuble", description: "Diagnostic et réparation de vos meubles abîmés", price: 15000, currency: "FCFA" },
    ],
    openingHours: {
      Lun: { open: "07:30", close: "18:00", closed: false },
      Mar: { open: "07:30", close: "18:00", closed: false },
      Mer: { open: "07:30", close: "18:00", closed: false },
      Jeu: { open: "07:30", close: "18:00", closed: false },
      Ven: { open: "07:30", close: "18:00", closed: false },
      Sam: { open: "08:00", close: "14:00", closed: false },
      Dim: { open: "00:00", close: "00:00", closed: true },
    },
  },
  {
    id: "b4",
    name: "Clinique du Quartier",
    category: "health",
    categoryIcon: "heart",
    description: "Consultations médicales générales, pédiatrie et soins infirmiers à domicile disponibles.",
    phone: "+228 99 45 67 89",
    address: "Boulevard de la Paix N°45",
    city: "Lomé",
    rating: 4.6,
    reviewCount: 203,
    isOpen: false,
    openHour: "08:00",
    closeHour: "18:00",
    hasDelivery: false,
    distance: "2.1 km",
    isVerified: true,
    services: [
      { id: "s13", title: "Consultation Générale", description: "Consultation médicale générale avec ordonnance", price: 5000, currency: "FCFA" },
      { id: "s14", title: "Prise de Sang", description: "Prélèvement et analyse en laboratoire partenaire", price: 8000, currency: "FCFA" },
      { id: "s15", title: "Soins Infirmiers Domicile", description: "Infirmier à domicile pour pansements, injections", price: 7500, currency: "FCFA" },
    ],
    openingHours: {
      Lun: { open: "08:00", close: "18:00", closed: false },
      Mar: { open: "08:00", close: "18:00", closed: false },
      Mer: { open: "08:00", close: "18:00", closed: false },
      Jeu: { open: "08:00", close: "18:00", closed: false },
      Ven: { open: "08:00", close: "18:00", closed: false },
      Sam: { open: "09:00", close: "13:00", closed: false },
      Dim: { open: "00:00", close: "00:00", closed: true },
    },
  },
  {
    id: "b5",
    name: "TechPro Solutions",
    category: "tech",
    categoryIcon: "monitor",
    description: "Réparation téléphones, ordinateurs. Création sites web et applications mobiles.",
    phone: "+228 98 56 78 90",
    address: "Rue de la Technologie, Tokoin",
    city: "Lomé",
    rating: 4.4,
    reviewCount: 76,
    isOpen: true,
    openHour: "09:00",
    closeHour: "20:00",
    hasDelivery: true,
    distance: "1.8 km",
    isVerified: false,
    services: [
      { id: "s16", title: "Réparation Smartphone", description: "Changement écran, batterie, diagnostic complet", price: 15000, currency: "FCFA" },
      { id: "s17", title: "Réparation PC", description: "Nettoyage, mise à jour, virus, écran cassé", price: 20000, currency: "FCFA" },
      { id: "s18", title: "Création Site Web", description: "Site vitrine professionnel, 5 pages + hébergement 1 an", price: 150000, currency: "FCFA" },
    ],
    openingHours: {
      Lun: { open: "09:00", close: "20:00", closed: false },
      Mar: { open: "09:00", close: "20:00", closed: false },
      Mer: { open: "09:00", close: "20:00", closed: false },
      Jeu: { open: "09:00", close: "20:00", closed: false },
      Ven: { open: "09:00", close: "20:00", closed: false },
      Sam: { open: "09:00", close: "18:00", closed: false },
      Dim: { open: "00:00", close: "00:00", closed: true },
    },
  },
  {
    id: "b6",
    name: "Plomberie Express",
    category: "artisan",
    categoryIcon: "tool",
    description: "Interventions rapides pour fuites, robinetterie, installation sanitaire. Disponible 7j/7.",
    phone: "+228 90 67 89 01",
    address: "Quartier Adidogomé",
    city: "Lomé",
    rating: 4.3,
    reviewCount: 41,
    isOpen: true,
    openHour: "07:00",
    closeHour: "21:00",
    hasDelivery: false,
    distance: "4.2 km",
    isVerified: false,
    services: [
      { id: "s19", title: "Réparation Fuite", description: "Détection et réparation de fuite d'eau urgente", price: 10000, currency: "FCFA" },
      { id: "s20", title: "Installation Robinetterie", description: "Pose robinet, mitigeur, douche", price: 15000, currency: "FCFA" },
      { id: "s21", title: "Débouchage Canalisations", description: "Débouchage WC, évier, siphon", price: 8000, currency: "FCFA" },
    ],
    openingHours: {
      Lun: { open: "07:00", close: "21:00", closed: false },
      Mar: { open: "07:00", close: "21:00", closed: false },
      Mer: { open: "07:00", close: "21:00", closed: false },
      Jeu: { open: "07:00", close: "21:00", closed: false },
      Ven: { open: "07:00", close: "21:00", closed: false },
      Sam: { open: "07:00", close: "21:00", closed: false },
      Dim: { open: "08:00", close: "18:00", closed: false },
    },
  },
];

export const MOCK_BOOKINGS: Booking[] = [
  {
    id: "bk1",
    businessId: "b2",
    businessName: "Salon Élégance & Style",
    businessCategory: "beauty",
    serviceName: "Coiffure Femme",
    servicePrice: 5000,
    date: "2026-06-20",
    time: "10:00",
    status: "confirmed",
    createdAt: "2026-06-15T09:00:00Z",
  },
  {
    id: "bk2",
    businessId: "b4",
    businessName: "Clinique du Quartier",
    businessCategory: "health",
    serviceName: "Consultation Générale",
    servicePrice: 5000,
    date: "2026-06-22",
    time: "09:00",
    status: "pending",
    createdAt: "2026-06-14T14:30:00Z",
  },
  {
    id: "bk3",
    businessId: "b1",
    businessName: "Restaurant Chez Mamie",
    businessCategory: "restaurant",
    serviceName: "Fufu & Soupe Graine",
    servicePrice: 2500,
    date: "2026-06-10",
    time: "12:30",
    status: "completed",
    createdAt: "2026-06-08T10:00:00Z",
  },
];

export const MOCK_ORDERS: Order[] = [
  {
    id: "o1",
    businessId: "b1",
    businessName: "Restaurant Chez Mamie",
    businessCategory: "restaurant",
    items: [
      { title: "Fufu & Soupe Graine", quantity: 2, price: 2500 },
      { title: "Boisson Locale", quantity: 2, price: 500 },
    ],
    total: 6000,
    status: "completed",
    deliveryMethod: "gozem",
    createdAt: "2026-06-12T13:00:00Z",
  },
  {
    id: "o2",
    businessId: "b5",
    businessName: "TechPro Solutions",
    businessCategory: "tech",
    items: [{ title: "Réparation Smartphone", quantity: 1, price: 15000 }],
    total: 15000,
    status: "in_delivery",
    deliveryMethod: "yango",
    createdAt: "2026-06-17T10:30:00Z",
  },
];

export const TIME_SLOTS = [
  "08:00", "08:30", "09:00", "09:30", "10:00", "10:30",
  "11:00", "11:30", "12:00", "12:30", "13:00", "13:30",
  "14:00", "14:30", "15:00", "15:30", "16:00", "16:30",
  "17:00", "17:30", "18:00",
];

export const formatPrice = (price: number, currency: string = "FCFA") =>
  `${price.toLocaleString("fr-FR")} ${currency}`;

export const formatDate = (dateStr: string) => {
  const date = new Date(dateStr);
  return date.toLocaleDateString("fr-FR", { weekday: "long", day: "numeric", month: "long" });
};
